routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('cars')->name('cars.')->group(function () {
    Route::get('/', 'CarsController@index')->name('index');
    Route::get('/create', 'CarsController@create')->name('create');
    Route::get('{id}', 'CarsController@show')->name('show');
    Route::get('{id}/edit', 'CarsController@edit')->name('edit');
    Route::put('{id}', 'CarsController@update')->name('update');
    Route::post('/', 'CarsController@store')->name('store');
    Route::delete('/', 'CarsController@destroy')->name('destroy');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CarsController.php
<?php

namespace App\Http\Controllers;

use App\Entities\Car;
use App\Http\Requests\CarRequest;
use App\Repositories\CarRepository;
use Illuminate\Http\Request;

class CarsController extends Controller
{
    /**
     * @var CarRepository
     */
    private $cars;

    /**
     * CarsController constructor.
     * @param CarRepository $cars
     */
    public function __construct(CarRepository $cars)
    {
        $this->cars = $cars;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $cars = $this->cars->getAll();

        return view('cars.index', ['title' => 'Cars List', 'cars' => $cars->toArray()]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('cars.create', ['title' => 'Create Car', 'car' => (new Car([]))->toArray()]);
    }

    /**
     * @param $id
     * @param string $view
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id, $view = 'show')
    {
        $car = $this->cars->getById($id);

        abort_if(! $car, 404);

        return view("cars.$view", ['title' => $car->getModel(), 'car' => $car->toArray()]);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        return $this->show($id, 'edit');
    }

    /**
     * @param $id
     * @param CarRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function update($id, CarRequest $request)
    {
        $car = $this->cars->getById($id);

        abort_if(! $car, 404);

        $updatedCar = new Car(array_merge($car->toArray(), $request->except('id')));
        $updatedCar->setId($id);

        $this->cars->update($updatedCar);

        return $this->show($id);
    }

    /**
     * @param CarRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function store(CarRequest $request)
    {
        $car = new Car($request->all());
        $this->cars->addItem($car);

        return $this->index();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function destroy(Request $request)
    {
        abort_if(! $this->cars->getById($request->get('id')), 404);

        $this->cars->delete($request->get('id'));

        return $this->index();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/cars/_form.blade.php
{!! csrf_field() !!}

<div class="form-group @if ($errors->has('model')) has-error @endif">
    <label for="model">Model</label>
    <input value="{{ old('model') ?? $car['model'] }}" type="text" class="form-control" name="model" id="model" placeholder="Model">

    @if ($errors->has('model'))
        <span class="help-block">{{ $errors->first('model') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('registration_number')) has-error @endif">
    <label for="registration_number">Registration Number</label>
    <input value="{{ old('registration_number') ?? $car['registration_number'] }}" type="text" class="form-control" name="registration_number" id="registration_number" placeholder="Registration Number">

    @if ($errors->has('registration_number'))
        <span class="help-block">{{ $errors->first('registration_number') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('year')) has-error @endif">
    <label for="year">Year</label>
    <input value="{{ old('year') ?? $car['year'] }}" type="text" class="form-control" name="year" id="year" placeholder="Year">

    @if ($errors->has('year'))
        <span class="help-block">{{ $errors->first('year') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('color')) has-error @endif">
    <label for="color">Color</label>
    <input value="{{ old('color') ?? $car['color'] }}" type="text" class="form-control" name="color" id="color" placeholder="Color">

    @if ($errors->has('color'))
        <span class="help-block">{{ $errors->first('color') }}</span>
    @endif
</div>

<div class="form-group @if ($errors->has('price')) has-error @endif">
    <label for="price">Price</label>
    <input value="{{ old('price') ?? $car['price'] }}" type="text" class="form-control" name="price" id="price" placeholder="Price">

    @if ($errors->has('price'))
        <span class="help-block">{{ $errors->first('price') }}</span>
    @endif
</div>

<button type="submit" class="btn btn-default">Save</button>

resources/views/cars/create.blade.php
@extends('layouts.master')

@section('content')
    <h2>{{ $car['model'] }}</h2>

    <form action="{{ route('cars.store') }}" method="POST">
        @include('cars._form', compact('car'))
    </form>
@endsection

resources/views/cars/edit.blade.php
@extends('layouts.master')

@section('content')
    <h2>{{ $car['model'] }}</h2>

    <form action="{{ route('cars.update', $car['id']) }}" method="POST">
        {{ method_field('PUT') }}

        @include('cars._form', compact('car'))
    </form>
@endsection

resources/views/cars/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="list-group">
        @forelse($cars as $car)
            <a class="list-group-item" href="{{ route('cars.show', $car['id']) }}">
                {{ $car['model'] }} [{{ $car['color'] }}] — ${{ $car['price'] }}
            </a>
        @empty
            <p class="list-group-item">No cars</p>
        @endforelse
    </div>
@endsection

resources/views/cars/show.blade.php
@extends('layouts.master')

@section('content')
    <h2>{{ $car['model'] }}</h2>
    <p><strong>Year</strong>: {{ $car['year'] }}</p>
    <p><strong>Registration number</strong>: {{ $car['registration_number'] }}</p>
    <p><strong>Color</strong>: {{ $car['color'] }}</p>
    <p><strong>Price</strong>: ${{ $car['price'] }}</p>

    <a href="{{ route('cars.edit', $car['id']) }}" class="btn btn-default edit-button" style="display: inline-block">Edit</a>
    <form action="{{ route('cars.destroy') }}" method="POST" style="display: inline-block">
        <input type="hidden" name="id" value="{{ $car['id'] }}">
        {{ method_field('DELETE') }}
        {{ csrf_field() }}
        <button type="submit" class="btn btn-danger delete-button">Delete</button>
    </form>
@endsection

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $title ?? 'Cars' }}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand">Cars Service</a>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="@if (request()->url() === route('cars.index')) active @endif">
                        <a href="{{ route('cars.index') }}">Cars list</a>
                    </li>
                    <li class="@if (request()->url() === route('cars.create')) active @endif">
                        <a href="{{ route('cars.create') }}">Add</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @yield('content')
    </div>
</body>
</html>